### ISSUE TITLE
Changing the starting postion of the hand

### ISSUE THREAD

**Issue by Scherady** [OpenGP/htrack#10]
Now the starting position corresponds to the camera looking a the internal face of the hand with the fingers pointing upwards. For my application I need to start with camera looking at the external side of the hand with the fingers pointing downwards.
Please advice.
Thank you.

**Comment by ataiya** [comment]
skeleton->set(_thetas); with the angle for the root joint rotated to whatever you want.
If I recall correctly the first six DOF are [tx,ty,tz,rx,ry,rz]

**Comment by Scherady** [comment]
My set up is not optimal, I have loaded a video to dropbox:
https://www.dropbox.com/s/5vvwugu6v27qp1b/20150924_232212.mp4?dl=0
Please advice what optimisation measures I could take.
Thank you

**Comment by ataiya** [comment]
Hi, what is happening is that re-initialization is kicking in WAYYYY to often.
There is a setting to lower the senitivity of the failure detection, perhaps @anastasia-tkach can tell you exactly where, but if I recall it should be in the UI.

I think your Depth camera is a different model from ours!!

**Comment by Scherady** [comment]
1. Could it be that my camera is more sensitive to failure detection than the one you used?
2. Would this explain why I need to adjust the sensitivity? 
3. I am trying to figure out where to do so :)

Thank you

**Comment by ataiya** [comment]
1. possibly, if the model is not exactly what we used
2. yes
3. there should be an option in the user interface

The simplest way of testing it out is disabling re-initialization after the first pose has been set.
After doing that, it will be pure registration/tracking!

**Comment by Scherady** [comment]
Hi,
I am still trying, here is an extract of the Application Output:
*******************************
...
component[0]: 76800
!!!WARNING not found anything useful 
no useful data 
no useful data 
no useful data 
no useful data 
no useful data 
no useful data 
no useful data 
component[0]: 76790
component[1]: 10
NEW useful data => reinit
Worker::initialize_offset 
component[0]: 76726
component[1]: 2
component[2]: 70
component[3]: 1
component[4]: 1
component[0]: 76700
component[1]: 100
component[0]: 76697
component[1]: 103
component[0]: 76695
component[1]: 105
component[0]: 76668
...
*******************************
I need some clues, may be @anastasia-tkach can help.
Thank you
