### ISSUE TITLE
Cannot build htrack for debuging -  Breakpoints skipped

### ISSUE THREAD

**Issue by Scherady** [OpenGP/htrack#11]
Not stopping on breakpoints. 

Googled but found no real solution and this message persists:

****************************************************
This does not seem to be a "Debug" build.
Setting breakpoints by file name and line number may fail.

Section .debug_info: Not found.
Section .debug_abbrev: Not found.
Section .debug_line: Not found.
Section .debug_str: Not found.
Section .debug_loc: Not found.
Section .debug_range: Not found.
Section .gdb_index: Not found.
Section .note.gnu.build-id: Found.
Section .gnu.hash: Found.
Section .gnu_debuglink: Not found.

***************************************************
Any help?
Thank you

**Comment by ataiya** [comment]
CMAKE_BUILD_TYPE

**Comment by Scherady** [comment]
In  ConfigureCompiler.cmake:

*******************************************************
# set(CMAKE_BUILD_TYPE "Release") #<<< FORCE SET
set(CMAKE_BUILD_TYPE "Debug")  #<<< FORCE SET 
*******************************************************
did not help.
Thank you

**Comment by ataiya** [comment]
Hi, it was working for me, so I am not sure I can help you with that.
That's a GDB / QtCreator / g++ problem, it's not related to our code.

**Comment by Scherady** [comment]
Hi,
I solved it yesterday:
1. Projects tab ->Build & Run page--> Build Settings -> Edit build configuration: Debug --> Add
2. Exit Qt
3. delete CMakeLists.txt.user
4. qtcreator CMakeLists.txt
5. re-configure
6. clean project
7. run cmake
8. build for debug :)
Thank you
