### ISSUE TITLE
Changing the size and the position of the palm in the hand model

### ISSUE THREAD

**Issue by Scherady** [OpenGP/htrack#12]
I want to adjust the model to fit better the morphology of my hand.
1. Changing the proportions in cylinders.cpp does not seem to affect the rendered model. Is this normal?
2. I found the possibility to change the size of the palm in line 179 of cylinders_renderer.cpp; but it alters the relative position of the fingers. I taught I could change the position of the palm, how could I do that and where?
Thank you.

**Comment by ataiya** [comment]
There are keyboard shortcuts to change the basic proportions of the hand (in the main.cpp of atb)
The best way to understand how it was done is by looking what is done there

**Comment by Scherady** [comment]
Thank you

**Comment by Scherady** [comment]
Is there a possibility to save the proportions of the hand once set?

**Comment by ataiya** [comment]
I think so. Search for save/load "calibration"

**Comment by Scherady** [comment]
The proportions set by the keyboard during runtime do not seem to affect the fitting but only the displayed hand model! 
1. I found the possibility to change the phalanges length but not the palm sizes and relative position.
2. Also I did not find where to change the diameters of the fingers. 
3. Are they set externally?
Thank you
