### ISSUE TITLE
Joints diameters 

### ISSUE THREAD

**Issue by Scherady** [OpenGP/htrack#13]
Where are the joints diameters defined ?
I commented out in "cylinders.cpp" the whole section where segment[i].radius1, radius2, radius1_y and radius2_y are defined. Strangely it  still works, suggesting they are defined somewhere else; but where?
Thank you

**Comment by Scherady** [comment]
Found: default.calib

**Comment by ataiya** [comment]
Great :)

Matthias wrote the hand data structure. I myself follow the same process. 
I start from the rendering class, and I backtrack the location of the data.
