### ISSUE TITLE
Calib file

### ISSUE THREAD

**Issue by qdesmedt** [OpenGP/htrack#14]
Hello,

Firstly, thanks for sharing your code.

Secondly, could you explain a bit the default.calib file ? 
Especially the first four lines ?

root root 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
pose root 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
scale pose 0.811646 0 0 0 0 0.811646 0 0 0 0 0.811646 0 0 0 0 1
Hand scale 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1

I have no problem with the rest of the file, (if I understood correctly, it should be  "Node - ParentNode - 3D transform matrix"). But these first four lines are a bit confusing.

Thanks a lot for your future response.

Ps:
I'm a PhD student, i'm currently making a hand's gesture database and i would like to use your software to improve the skeleton of an intel real sense camera with the "Optimization until convergence" part of your code.

**Comment by ataiya** [comment]
I'd not decode that by hand, have you looked at the Calibration IO file?
That should give you a much better idea.

https://github.com/OpenGP/htrack/blob/747b40f7a07f2bc0530587fae8dcf6fa31d25ee1/tracker/Calibration/Calibration.cpp
