### ISSUE TITLE
Crash in PixelIndexer.h

### ISSUE THREAD

**Issue by RF83** [OpenGP/htrack#15]
Hello,

I've built the code using VS2013 with a Real Sense F200 camera and a GeForce GTX 960. My system is:
Windows 8.1 Pro 64-bit
DirectX 11.0
Graphics Driver v. 358.87
Cuda 7.5

When I run either htrack_qt or htrack_atb I get a crash in cudax/PixelIndexer.h line 77:

thrust::for_each(meshgrid->begin(), meshgrid->end(), functor);

If I comment that line I don't get any crash but, not surprisingly perhaps, the tracking is not working at all.

Any hints or suggestions on what is going wrong and how I can fix this issue ?

Many thanks in advance,

Samantha

**Comment by ataiya** [comment]
Hard to say as so many are running it without crashes.

I think you mean line 71 on my github code:
```
    void exec(){
        clear();
        Functor functor(counters, render_indexes, sensor_indexes, cnstr_indexes);
        thrust::for_each(meshgrid->begin(), meshgrid->end(), functor);
    }
```

Have you checked that the argument passed to the functor are valid?
You can verify that they are not-null, for example.

**Comment by RF83** [comment]
Hello ataiya,

Many thanks for trying to help out! Indeed the pointers are marked as null when I trace the code but VS also says 'unable to read memory' so I am not sure if they are null or not... Any idea on why those raw pointers might be null ?

I am also curious to know if the code is tested and works (although slower) in Windows and with a Real Sense F200 camera ? Maybe I should try to build in Ubuntu ?

**Comment by ataiya** [comment]
Hi, 

hard to say. Yes, we did have it working on windows, but the performance was not good at all (windows interferes with frequent cuda launches creating delays).

Absolutely, I'd *strongly* recommend you to use ubuntu.

**Comment by Scherady** [comment]
I did not succeed to get Intel Real Sense F200 Camera working on Ubuntu, have you?

**Comment by ataiya** [comment]
No, somebody from Intel told me they are working on Android/Linux drivers though.

**Comment by RF83** [comment]
Hi ataiya.

I just successfully built on Ubuntu but like I said I have an Intel Real Sense F200 (or Kinect V2). Can you please tell me which sensor(s) are working / tested on Ubuntu ?

Many thanks,

Samantha

**Comment by ataiya** [comment]
This is what we used:
https://i.ytimg.com/vi/Kms0zEXpYN4/maxresdefault.jpg
