### ISSUE TITLE
What camera model ?

### ISSUE THREAD

**Issue by Scherady** [OpenGP/htrack#16]
What is exactly the camera model you are using?

I am using the Creative Senz3D™ 
![20130905_creativecamerasenz3d](https://cloud.githubusercontent.com/assets/12855927/11036831/fa7dce6e-86fa-11e5-9f01-6af3fdad9cee.jpg)

http://www.softkinetic.com/AboutUs/NewsEvents/ArticleView/ArticleId/289/Creative-Senz3D-Interactive-Gesture-Camera-available-for-online-order-in-the-US-from-Sept-25

My camera does not seem to behave like yours.
I have not succeed to stabilize the image [OpenGP/htrack https://github.com/OpenGP/htrack/issues/10]

**Comment by ataiya** [comment]
Here you go, I took a picture of the camera we use:
![outcamera](https://cloud.githubusercontent.com/assets/4480573/11127701/67aa3f50-892a-11e5-8f38-a5f730684413.jpg)

**Creative Labs, Model# VF0780**

**Comment by Scherady** [comment]
I use the exact same model, therefore the continuous instabilities must be due to something else.

**Comment by ataiya** [comment]
what do you mean by "instability"? Are you talking about the fact that this **window with the colored segments** keep popping up?

That's the **re-initialization** procedure being triggered *way* too often. The coefficients that control that component are learned from data, but I am quite surprised that with the same camera it does not work well! As I said, the simplest solution is to manually disable it from the UI - then you know where your problem lies.

**Comment by Scherady** [comment]
I am not sure where and how to "manually disable it from the UI" :(

**Comment by ataiya** [comment]
In the main tracking file, lines [106..110]:
https://github.com/OpenGP/htrack/blob/master/tracker/Tracker.h

The code is self-explanatory. 
Find out where this is controlled from the AntTweakBar and that's it!

(sorry but I don't have my hands on a dev machine right now, I don't recall what exactly the UI looks like)

**Comment by Scherady** [comment]
Also what are the characteristics of the ambient illumination you recommend?

**Comment by Scherady** [comment]
Hi
Please watch this new video:
https://www.dropbox.com/l/s/5PQ4wtvviDY33FxOBHGsKs
Can we obtain better than this?
Thank you

**Comment by ataiya** [comment]
**Yes, absolutely**. For example, this is a recording of our live demo at SGP:
https://www.dropbox.com/s/k45lh3gfx3iroga/sgp%20demo%20session.mp4?dl=0

As I told you the “FindFingers” is being invoked way too often.
You can disable it after initialization (from the UI) to see how well it runs.

**Comment by Scherady** [comment]
Sorry but I am not sure I understand what you mean by "from the UI" :(
Thanks

**Comment by Scherady** [comment]
Besides since I am using the same software with the same camera as you, I should expect the same results as you without having to change anything, isn’t it?

**Comment by Scherady** [comment]
OK
For some reason only a small part of AntTweakBar menu was appearing on the window that additionally was not reachable with the mouse because of an offset.
To resolve these difficulties I had to:
1.  adjust the position and the size of the menu by:
****************************************
    void initializeGL(){
        std::cout << "GLWidget::initializeGL()" << std::endl;
        initialize_glew();
        tw_settings->tw_init(this->width(), this->height()); ///< FIRST!!
        //IC// Adjust TwBar position and size
        TwDefine(" Settings position= '10 300'");
        TwDefine(" Settings size= '200 600'");
        //IC// END
        glEnable(GL_DEPTH_TEST);
*********************************************
and
2. Off set the y-position of the mouse by 240:
************************************************
            case QEvent::MouseMove:
                //IC// Correct mouse offset
                //event_on_atb = TwMouseMotion(me->pos().x(), me->pos().y());
                event_on_atb = TwMouseMotion(me->pos().x(), me->pos().y()+ 240);
                //IC//END
                // qDebug() << "Move" << status << e->pos();
                break;
***************************************
Now that the UI menu is visible and reachable could you please let me know which parameter(s) of this menu I should change to disable the “FindFingers” after initialization. 

![screenshot from 2015-11-18 17 36 02](https://cloud.githubusercontent.com/assets/12855927/11247450/6e7c6b40-8e1c-11e5-82fb-936bde32ab10.png)

Thank you

**Comment by ataiya** [comment]
It's **DetectOn** -- notice earlier I mentioned this snippet of code:
```
 if(init_enable && track_failed ){            
            static QianDetection detection(worker);
            if( detection.can_reinitialize() )
                detection.reinitialize();
        }
```

**Comment by Scherady** [comment]
I have loaded a video testing the effect of DetectOn.
I started with DetectOn checked (on), turned it off then on and later off again:
https://www.dropbox.com/s/kelpguizw61c7dh/htrack-DetecOn-Test.mp4?dl=0
Thank you

**Comment by Scherady** [comment]
Hi
Your video is impressive:
https://www.dropbox.com/s/k45lh3gfx3iroga/sgp%20demo%20session.mp4?dl=0
I cannot reproduce it :(
Even though you have the Intel RealSense box displayed, as far as I discern from the video, you seam to actually use the Creative Senz3D.

Do you plan to demonstrate your system somewhere in Europe in the near future or is there a possibility to see it in operation in your lab? I would take a day off and come over.
Thank you

**Comment by ataiya** [comment]
Yes, we just used the box to carry the sensors to the conference venue.

You could visit EPFL and Anastasia would be able to show it to you. I have
just left EPFL and started a new job in Victoria (Canada).

**Comment by Scherady** [comment]
Well I wish you the best in your new job.

How do I contact Anastasia?

**Comment by ataiya** [comment]
http://lgg.epfl.ch/people.php
