### ISSUE TITLE
does it support intel realsense

### ISSUE THREAD

**Issue by shomedas** [OpenGP/htrack#18]
Does htrack support intelrealsense camera?[intelrealsense](https://software.intel.com/en-us/realsense/sr300camera).

Does it support carmine 1.09?

I have access to only these two sensors.

**Comment by ataiya** [comment]
"support" is a big word. It will run with the carmine, but the magic numbers for tracking failure detection are not tuned to the carmine (so reinitialization will fire randomly). Realsense was just released for linux, we had attempted to have it on windows, but we had a lot of problems with CUDA performance.

**Comment by shomedas** [comment]
Sorry but I couldnt understand your reply.
I am running linux(ubuntu 14.04 64bit). Will htrack work with intelrealsense?

**Comment by ataiya** [comment]
The answer is yes/no. It will execute, but performance will be very highly suboptimal.
