### ISSUE TITLE
Building feedback

### ISSUE THREAD

**Issue by tvandenzegel** [OpenGP/htrack#2]
Really cool! And thank you for sharing the source code! Learning a lot!

I'm still digging through the code in order to understand everything. But it seems you really need a strong graphics card, I only get 7 fps :( And tracking seems to be pretty shaky with a creative senz camera. :/

Just some feedback about the build process, just so that the next person doesn't struggle as I did. :)
- Maybe mention that you have to build it in x64-bit. I first built it in 32bit but  because I don't have any experience with cuda I didn't know that some libraries are 64bit only. Also the serialization is somewhere broken in 32bit (in posespace.cpp the size of sizeof(typename Matrix::Index) is 4byte in 32bit and 8byte  in 64bit I think).
- CUDA needs to be enabled. There are preprocessor definitions USE_CUDA, so from the beginning I assumed that I could run it without cuda, but this is not the case. :) 
Is the LegacyTracker in the code a cpu version of the current implemented gpu tracker?
- Isn't there something wrong with the cmake configuration? (I'm a cmake beginner) I had to give the path for each lib in opencv instead of just one path to opencv. The same for Qt.

**Comment by ataiya** [comment]
Hey! 

Let me get back to you Friday. I'm currently on vacation at the sea! Yah you need a good one (gtx980 as mentioned in the paper, not really because of performance, but because of bugs they had in other cards on compute/render context switching).

**Comment by ataiya** [comment]
[international relocation finished, I'll have discontinuous access to WiFi now]

"you really need a strong graphics card, I only get 7 fps"
I made a note that to achieve the performance you see in the video you need a GTX980 and a 4GhZ i7.

"Maybe mention that you have to build it in x64-bit."
Updated on the project landing page.

"Is the LegacyTracker in the code a cpu version of the current implemented gpu tracker?" 
No, it's [Shroder ICRA'13]

"CUDA needs to be enabled"
Yes, it is mandatory, but it's quite useful to turn it off as CUDA takes much longer to build.

"Isn't there something wrong with the cmake configuration?"
What is wrong is that neither OpenCV nor CMake provide an "official" FindPackage. If you find one that you think works better let me know and I'll test it out

Let me know if you have further questions.

**Comment by tvandenzegel** [comment]
Thank you for your reply!
