### ISSUE TITLE
Error when executed htrack_atb & htrack_qt

### ISSUE THREAD

**Issue by Armixy** [OpenGP/htrack#20]
When I want to executed it, I got these information:
![image](https://cloud.githubusercontent.com/assets/6630789/16065178/26b1d54e-325d-11e6-974e-621db049428f.png)

---
**Files of executable folder:**
![image](https://cloud.githubusercontent.com/assets/6630789/16065230/be1e296e-325d-11e6-8690-c544f2ecaeda.png)

---
**I've searched a lot of materials on google, and even copy all the plugins files and platforms files into current folder, but still not work. Can anyone help me? Really appreciate it!**

**Comment by ataiya** [comment]
Don't use the qt one, use htrack_atb.
The qt is to run quantiative comparison and do frame-by-frame inspection.

**Comment by Armixy** [comment]
@ataiya But I got the same error when I ran htrack_atb.

**Comment by ataiya** [comment]
Sorry but I have no idea. 
This is a Qt issue, google would know as much as I do.

**Comment by Armixy** [comment]
@ataiya I have searched a lot on google, tried a lot of answers of this problem, still cannot work. The same error info.

**Comment by ataiya** [comment]
Sorry, I can hardly fix a problem that I have never seen and cannot reproduce. 
Further, it is slightly concerning you are trying to run htrack on a laptop when we made the execution requirements pretty clear (beefy PC).

**Comment by Armixy** [comment]
Well, I have fixed it by uninstalling all the qt components and reinstall Qt5.4.1. Thank you for your help. :-)
