### ISSUE TITLE
htrack_qt shows no output

### ISSUE THREAD

**Issue by shomedas** [OpenGP/htrack#23]
I have successfully compiled both htrack_qt and htrack_atb. The htrack_atb shows the hand along with the depth image in green. The tracking is not perfect.

The htrack_qt shows no output. it shows two small black windows on a big white window and a hand template.

How do I use the two compiled executables? Any brief explanation would be helpful.

the images for htrack_qt:
![htrack_qt](https://cloud.githubusercontent.com/assets/14357750/17260507/6f301100-55ee-11e6-8188-4f954898c95e.png)

the image for htrack_atb:
![htrack_atb](https://cloud.githubusercontent.com/assets/14357750/17260523/879105f6-55ee-11e6-81f2-96c3ce666d66.png)

**Comment by hum2bahrian** [comment]
For htrack_qt just click LIVE to run the software. For the black window, the right one is the depth camera window and the left one is color camera.

Tracker, I also can't figure out what is the proper settings for nicer tracking

**Comment by ataiya** [comment]
I now honestly wish I had removed all the components (including
cross-platform compile) that people are not supposed to use (like the _qt
which is mostly to run and scrub/inspect datasets).

Further, I'll actually add a guard that detects <60Hz performance (aka you
are not using sufficiently good hardware) and completely halt the system -
this is starting to annoy me - the paper clearly states the minimal spec,
and you cannot expect a perfect tracking from a full model based tracker if
you don't match the hardware we describe.

*So tell me, what are you running on exactly? (exact CPU / GPU / RAM)*

>

**Comment by ataiya** [comment]
I can tell you your wristband segmetation is completely off (by just looking at the segmented image). See the debug flags show_hand and show_wband. Those can give you an idea whether the wristband is detected properly or not. It should be solid colored and clearly a nice palm segmentation.

Once that is fixed, then you have to adjust the template to your size (right now it's really, really off).

Finally I can already see the you are not gonna get good performance... you are running at 30FPS!!! Look at the UI, it's mentioned in there. It's a temporal tracker, it needs high frequency sensor data (e.g. primesense even offers 120 FPS!)

**Comment by shomedas** [comment]
I am using :

i7-4770k(32GB RAM) + Nvidia-titanX + carmine 1.09

**Comment by ataiya** [comment]
Mhh I don't know how the titanX compares to the GTX980 (floating point specifically). I recall one of the Titans was specialized to double and not floating point.

But *assuming* it's superior then you have to make sure you are starting the right camera... There's parameters to have it run at 30 and 60... Cannot really recall the API but I am sure you can figure it out :) :)

My suggestion is to find yourself a Senz3D or wait a few weeks until we release htrack2.0 (SIGAsia conditionally accepted). A lot of the silly deadline hacks (eg wristband) will also be gone, and by December we'd have a CNN re-initializer fully integrated.

Say thanks to Canadian immigration for the fact that this was not done this summer... Sigh

**Comment by shomedas** [comment]
Sorry I have GTX TitanX, not Nvidia-Titanx(newly released)
GTX TitanX has better floating-point performance	than GTX 980 (6,144 GFLOPS vs 4,358 GFLOPS)

**Comment by ataiya** [comment]
Pretty sure you are loading the wrong camera then.

**Comment by ataiya** [comment]
> The video for tracking is as below:
> htrack_atb3.avi.tar.gz

The re-initializes is kicking in continously (see the black image popup). Note the software has **baked-in magic numbers** for the Senz3D (that tell the software when tracking has failed, and from the depth images I see I think you are using the carmine, which is not the configuration that is loaded in the software.

You can manually turn off the reinitializer from the UI, as you are using an uncalibrated system.
I am that close to trash all sensor support beside Senz3D. I am getting very tired of people not reading & respecting the required specs.
