### ISSUE TITLE
What are the good htrack_atb settings for better hand tracking

### ISSUE THREAD

**Issue by hum2bahrian** [OpenGP/htrack#24]
Thanks for making your code openSource. It's really helpful.

Can you please suggest what are good settings for Tracker like iters and iters(rigid)
I am using PrimeSense camera same as the video.

**Comment by ataiya** [comment]
>
> Thanks for making your code openSource. It's really helpful.
>
> Can you please suggest what are good settings for Tracker like iters and
> iters(rigid)
> I am using PrimeSense camera same as the video.
>
... I wish I could remember :)
(you have to keep in mind my dev machine was left behind at EPFL)

I'd say something like 2+8, just play around until you are happy.
I just swish somebody would help squeezing some performance in the system.
There are so many things that could be improved

>
