### ISSUE TITLE
Integrate libRealSense in htrack

### ISSUE THREAD

**Issue by ataiya** [OpenGP/htrack#26]
[This is where](https://github.com/OpenGP/htrack/tree/master/tracker/Sensor) the sensors are.

- [x] Compile [libRealSense](https://github.com/IntelRealSense/librealsense/blob/master/examples/cpp-pointcloud.cpp)
- [x] Test librealsese samples
- [x] Write a CMake file for htrack integration
- [x] Create the new camera interface Sensor_LibRealSense

**Comment by r4ghu** [comment]
Issue closed - Sensor_Librealsense is up and running!

**Comment by ataiya** [comment]
Can you Skype-sync with @anastasia-tkach and re-train the discriminative re-initializer for the new sensor? (see the Matlab folder) Once that's done, we'll be able to vomit training data for the convnets approach. I'll send you Anastasia's Skype/email via PM.
