### ISSUE TITLE
Train the re-initializer classifier for LibRealSense

### ISSUE THREAD

**Issue by ataiya** [OpenGP/htrack#27]
see matlab/ folder (you can get Matlab for free at UVic, ask somebody in the lab)
Ask @anastasia-tkach for instructions on how to get the data.

(Try to calibrate the model to your hand before you start, and save a calibration file in the path for yourself (auto-loaded at boot time). See the calibration shortcuts in the atb/main.cpp)

**Comment by r4ghu** [comment]
Completed!
