### ISSUE TITLE
Librealsense sensor noise at edges.

### ISSUE THREAD

**Issue by r4ghu** [OpenGP/htrack#28]
Please check the issue here: https://github.com/IntelRealSense/librealsense/issues/267

**Comment by ataiya** [comment]
For now let's fix this and the logistic regressor.
After that, fork the repo in a private one under your user please :)

**Comment by ataiya** [comment]
For now let's fix this and the logistic regressor.
After that, fork the repo in a private one under your user please :)

**Comment by r4ghu** [comment]
Issue solved! The problem is due to default anti-aliasing of the OpenCV's resize function.
