### ISSUE TITLE
Does it support CUDA8.0 with GTX1080?

### ISSUE THREAD

**Issue by Soledad89** [OpenGP/htrack#29]
I run into this error after launching the command: ./htrack_qt

htrack starting 
--Execution path:  /home/w00378682/Documents/DeepHand/htrack/build 
void QWindow::setTransientParent(QWindow*) QWidgetWindow(0x176c010, name = "QWidgetClassWindow") must be a top level window.
OpenGL_viewer::initializeGL() OpenGL 3 . 2 
Reading Wristband Colors from: /home/w00378682/Documents/DeepHand/htrack/build/wristband.txt
  hsv_min: [94, 111, 37, 0]
  hsv_max: [120, 255, 255, 0]
MapSMtoCores for SM 6.1 is undefined.  Default to use 192 Cores/SM
Starting up CUBLAS
Init cuda: 320 240
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  function_attributes(): after cudaFuncGetAttributes: invalid device function
Aborted (core dumped)
 
I suspect that this project does not support cuda8.0 with gtx1080. Anyone encounters this issue, please give me some advice.

**Comment by ataiya** [comment]
Should be.
see the cuda helloworlds, will help you narrow it down 
http://stackoverflow.com/questions/24067641/cuda-thrust-runtime-error-invalid-device-function

**Comment by Soledad89** [comment]
@ataiya Thank you for your reply. I have solved the problem. 
For anyone who may run into this issue using cuda8.0 with GTX1080, I list the solution below:
change the cmake/ConfigureCUDA.cmake line 49 to:
`set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -gencode arch=compute_50,code=sm_50 -gencode arch=compute_50,code=compute_50") # GTX1080`

**Comment by volley84** [comment]
@ataiya @Soledad89 Thank you for yours issues. I have GTX1060. 
What cmake/ConfigureCUDA.cmake line 49 and some line? I need your help for GTX1060  , you had gtx980 or gtx1080.
