### ISSUE TITLE
Error while executing htrack_atb

### ISSUE THREAD

**Issue by murasaki0110** [OpenGP/htrack#30]
![err](https://cloud.githubusercontent.com/assets/5639191/21253741/c2781414-c39b-11e6-88db-2ee685a17656.png)
The error messages I got are as above.
When execute ./htrack_atb, the camera can be turned on and a window with 3D blue hand model showed but immediately crushed into error.
Same error happens when execute ./htrack_qt and click the "LIVE" button.
Can anyone give some advices about this?

My settings:
Intel i7
nVidia GTX 1070 , CUDA 8
Ubuntu 16.04
OpenCV 2.4.13 build with QT5.7
Senz3d depth camera

**Comment by ataiya** [comment]
Yes, I can help you read the homepage and see that the library was released for *Linux*.
If you want windows, see our follow up: github.com/OpenGP/hmodel

**Comment by murasaki0110** [comment]
Um, I think I'm using Ubuntu.

**Comment by ataiya** [comment]
Very sorry then for my flaming attitude, I misread that.
Cannot really say I have seen this bug, sorry :\

**Comment by murasaki0110** [comment]
Thank you, it works after disable the error call in window_QT.cpp.
Then I have questions about the hand tracking.
It looks like this, the model can't fit my hand and keep jittering, which configuration or parameters should I changed?
![screenshot from 2016-12-19 10-45-23](https://cloud.githubusercontent.com/assets/5639191/21299815/35fad0e4-c5da-11e6-8681-bc51391dc667.png)
![screenshot from 2016-12-19 10-47-12](https://cloud.githubusercontent.com/assets/5639191/21299817/3b752ace-c5da-11e6-868d-a1bbc48df1c2.png)

**Comment by ataiya** [comment]
Compile with AntTweakBar, then in the UI there will be an entry for show_wband and show_hand. 
This will hope two windows, and the B/W image marking hand and wristband silhouettes showed therein should be stable and jitter free. If the wristband is not detected properly this will affect tracking brutally, and result in the re-initialization phase to kick in at every frame (i.e. the image on the top left keep changing). In a properly setup system re-initialization kicks in only once every few seconds.

Sorry, circumventing these issues was pure (lengthy) engineering, so we put no effort in making it better (yet)

**Comment by murasaki0110** [comment]
Great help for me to understand the paper and code. I tuned the wristband hsv color range and then tracked well. Nice work.
