### ISSUE TITLE
some questions about tracking result

### ISSUE THREAD

**Issue by asd2846531** [OpenGP/htrack#31]
Hi,

My name is Yi-Ting Chen, from National Chiao Tung University, Taiwan. I would like to thank you for sharing your code of gesture detection and tracking.

I managed to run the code, but I found that sometimes the result was not as good as that in the demo video. Here is how it looks like: 
https://www.youtube.com/watch?v=qPUWv_sRPyI

Do you have any idea what causes the problem? Did I miss anything important? The following image shows the hardware used in my setup, with the Intel RealSense camera. I hope it is helpful for you to know the problem.

![16-35-37](https://cloud.githubusercontent.com/assets/17698261/21523459/75780202-cd49-11e6-8a37-778132e90125.png)

Besides, I am confused about the sensing area of RealSense. In your demo video, the area seems quite large. But it is quite small in my setup. My hand frequently moves outside the area when using the gesture tracking system. Why is that?

Thank you for your patient, and I look forward to your kind reply.

**Comment by ataiya** [comment]
Hello there, the CPU, GPU and sensor are not the one that are declared on the homepage of the project. All three contribute to sub-optimal performance (especially the sensor). In the demo video we were using a primesense carmine, that has a larger range than then Senz3D.
