### ISSUE TITLE
How can framerate affect the tracking result?

### ISSUE THREAD

**Issue by yaoxinreaps** [OpenGP/htrack#33]
Thank you for your source codes. I installed the program and ran with a poor GPU of nvidia gt630. It seemed to run at less than 30 fps (how to see the FPS?) and the tracking result was not good (the size of hand model was adjusted to a proper value). So I doubt how can framerate affect the result? Thank you!

**Comment by ataiya** [comment]
It's a _model-based_ tracker that relies on temporal coherency, it's an effect to be completely expected from this class of algorithms.
