### ISSUE TITLE
function Joint::getEndPosition

### ISSUE THREAD

**Issue by zhangjiasy** [OpenGP/htrack#34]
Hi Guys，

I read your codes but had difficulty to understand.
1. In the funtion of joint::getEndPosition, what dose the parameter "force_y" mean?
[ https://github.com/OpenGP/htrack/blob/master/tracker/Legacy/geometry/Joint.cpp](url)
2. In the same function, how is the var "magic" calculated? why should the length minus the magic value.

**Comment by ataiya** [comment]
The hand data structure was inherited from @maschroe :)
@maschroe can you help him quickly? 

@zhangjiasy note github allows you to have links to the code, which is missing in your question
