### ISSUE TITLE
Is there a CPU code version of the fitting content?

### ISSUE THREAD

**Issue by yaoxinreaps** [OpenGP/htrack#35]
Hi,
I am reading your codes and get really confused about the fitting part which is written in GPU format. It makes me feel very hard to understand the computation procedure of 3D point correspondences and other details. So do you have a CPU code version which can be shared to us conveniently? Thank you!

**Comment by ataiya** [comment]
No, sorry. I am hoping to do something within the next year in regards

**Comment by yaoxinreaps** [comment]
Thank you all the same.
