### ISSUE TITLE
Does it support Realsense R200?

### ISSUE THREAD

**Issue by lucianowxc** [OpenGP/htrack#36]
Hi guys,
I'm a PhD student of Computer Science at University of São Paulo and I want to run and understand your code to help in my research. I was able to build the project and make htrack_atb and htrack_qt, but it seems that the application cannot access the sensor data, since the depth data is never shown in background for htrack_atb. Is it compatible with the sensor Intel Realsense R200?

I'm trying to execute the code at the following system configurations:
Intel® Core™ i7-6700K CPU @ 4.00GHz × 8 
NVidia GeForce GTX 970/PCIe/SSE2
Cuda 8.0
Debian GNU/Linux 8 (jessie) 64-bit

Thanks in advance for making the code available.

**Comment by ataiya** [comment]
are you wearing a blue wristband?

**Comment by lucianowxc** [comment]
Yes, although it is a paper blue wristband. I made sure its color is in the preset HSV interval.

**Comment by ataiya** [comment]
Hi Luciano, it's honestly a bit hard to say what is wrong from the information you provided.
If you are interested in testing the tracked sequences (no need for sensor), you can refer to our follow-up work: github.com/OpenGP/hmodel
