### ISSUE TITLE
Suitable cameras

### ISSUE THREAD

**Issue by Spatzi** [OpenGP/htrack#5]
Hi !

Just wanted to know if the code should work also with Kinect for Windows or XBOX 360 ?

Thanks

**Comment by tvandenzegel** [comment]
Hi,

It works with OpenNI compatible cameras. 
So a Microsoft Kinect on Windows should work normally. 
Just check the OpenNI website.

It does not work on XBOX360.

**Comment by Scherady** [comment]
Hi,
How about Creative DepthSense camera and Intel RealSense camera, do they also work?
According to htrack video they also work but they give different tracking results than the Kinect, don't they?
Thank you.

**Comment by ataiya** [comment]
[sorry for the radio silence -- international move & no wi-fi at home yet]

As @tvandenzegel mentioned it should **RUN (which is different from working well)** with any OpenNI cameras. More specifically as we are purely tracking the system work best at >60FPS.

- Optimization runs at 60FPS only on linux (the only OS that does not interfere with GPU kernel scheduling)
- The [SoftKinetic/Intel Senz3D](http://www.softkinetic.com/AboutUs/NewsEvents/ArticleView/ArticleId/289/Creative-Senz3D-Interactive-Gesture-Camera-available-for-online-order-in-the-US-from-Sept-25) is the best camera as it runs in Linux and at ~60FPS

Note that the re-initialization system is calibrated for the Senz3D, so if you want to try other sensors you should turn it off (typically it kicks in too often without proper calibration)!!!
