### ISSUE TITLE
Tracking all ten fingers of both hands

### ISSUE THREAD

**Issue by Scherady** [OpenGP/htrack#8]
For my application I need to track all ten fingers in real time while tapping on a surface; in need to track the coordinates of the fingertips and the locations of their taps.

1. htrack demo tracks one hand only: if possible how to track two hands?
2. is it possible to overcome the difficulties related to reflections on the surface while trying to track fingers in close vicinity of the surface?

**Comment by ataiya** [comment]
1) it is possible (with some restrictions, for example assuming they never overlap during motion) but it would require a bit of software engineering. Essentially, you'd have to generate the labeling for hand {1,2} and then instantiate two trackers (but you do this directly, but heavy mods to the code are necessary).

2) I am not too sure what "relfections on the surface" means?

**Comment by Scherady** [comment]
1) Yes during operation of the app the hands are not supposed to overlap. I can contribute the code modification efforts, if necessary.
2) Other solutions like Leap Motion fail to track the fingers in the vicinity of a surface partly because of the disturbances created by the reflections of the IR light on the surface.

**Comment by ataiya** [comment]
1) good luck!
2) if you graze the body too closely it will happen as well, not because of interference, but because the tracker will have difficulties differentiating geometry of the hand from the one of other objects.

**Comment by Scherady** [comment]
1) yes, huge challenge for sure :)
2) what do you recommend then?

**Comment by ataiya** [comment]
1) mild I'd say, most of the code is there
2) likely you'll have to use a skin classifier, see what Hao Li did recently on robust face tracking (SIG'15 and CVPR'15 papers)

**Comment by Scherady** [comment]
1) Fine !
2) Thank you for the information I will read his papers. Your idea is to use a skin classifier to better discriminate the fingers from the surface, isn't it? Why not use, for testing and ease of use at least for the beginning, OpenCV existing skin detection/segmentation capabilities? 
3) Does Hao Li's skin classifier present some particularly strong advantages?
4) Would adding a skin classifier to htrack affect the performance?
Thank you.

**Comment by ataiya** [comment]
2,3,4) these sound like research questions to me :)

Li uses "a" skin tracker to discriminate between face & {hair, glasses, etc}. 
You can use whatever you think works best.
