### ISSUE TITLE
htrack performance - Linux vs Windows

### ISSUE THREAD

**Issue by Scherady** [OpenGP/htrack#9]
It is reported that htrack performs significantly better under Linux than Windows.
1) Is that mainly due to the graphics routines ?
2) If 1)  is true (or partially) would disabling those routines, or replacing them with simpler ones, make the performance under windows more acceptable?
3) Reasons for my questions: (i) for my application I ultimately need only the coordinates of the finger-tips and (ii) I am having prohibitive difficulties to run htrack under Linux mainly due to clashes between newer versions of required library such a CUDA 7 and OpenCv 3.0.
Thank you

**Comment by ataiya** [comment]
1) I spoke with the NVIDIA engineers. On OSX they had a system bug, while on Windows the OS has a scheduling system for GPU kernels that creates massive delays. Linux has no such problems.
2) Downsampling depth images + re-writing some of the routines on the CPU side would work, yes
3) Yes, we used OpenCV 2.4

**Comment by Scherady** [comment]
1) In other words I better stick to Linux and try to solve my compilation problems. Isn't it?
2) Downsampling depth images would not be a good option for me as I need real time tracking of the fingers.
3) Should I try to use OpenCv 2.4 instead of 3.0 ?

**Comment by ataiya** [comment]
1) yes 2) not necessarily true with a short-range camera 3) yes

**Comment by Scherady** [comment]
2) Ah you mean down-sampling in number of points not in number of frames, yes?
4) If yes it might then affect the precision of the coordinates of the fingertips, yes?

**Comment by Scherady** [comment]
Hi, 
I solved the OpenCV unspecified error by rebuilding OpenCV, but I have a new error:
***********************************************
Starting /home/brian/Scherady/build-htrack-Desktop-Default/htrack_qt...
htrack starting 
--Execution path:  /home/brian/Scherady/build-htrack-Desktop-Default 
OpenGL_viewer::initializeGL() OpenGL 3 . 2 
Reading Wristband Colors from: /home/brian/Scherady/build-htrack-Desktop-Default/wristband.txt
  hsv_min: [94, 111, 37, 0]
  hsv_max: [120, 255, 255, 0]
Starting up CUBLAS
Init cuda: 320 240
Executed [Kernel Initialization] in [1.1215ms]
Loading PCA data from: /home/brian/Scherady/build-htrack-Desktop-Default/PoseSpace_PCA/
Calibration::autoload()
Loaded calibrated model from /home/brian/Scherady/build-htrack-Desktop-Default/default.calib
SensorDepthSenseGrabber::initialize()
Found 3 nodes
Waiting for data...  0 
OpenCV Error: Null pointer (NULL guiReceiver (please create a window)) in cvDestroyWindow, file /home/brian/opencv/modules/highgui/src/window_QT.cpp, line 497
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/brian/opencv/modules/highgui/src/window_QT.cpp:497: error: (-27) NULL guiReceiver (please create a window) in function cvDestroyWindow

The program has unexpectedly finished.
/home/brian/Scherady/build-htrack-Desktop-Default/htrack_qt crashed
***********************************************
Thank you

**Comment by ataiya** [comment]
again, not sure why you are using htrack_qt. Beside that, it seems you didn't compile OpenCV with the UI modules

**Comment by Scherady** [comment]
what is the difference between htrack_atb and htrack_qt?

**Comment by Scherady** [comment]
OK :)
1) helloworld_opencv works now, a window with emoticon :/ appears:
***************************************************
Starting /home/brian/Scherady/htrack-1/build-apps-Desktop-Default/helloworld_opencv/helloworld_opencv...
image size: 512 512
init done
opengl support available
************************************************** 

2) but htrack_atb still crash with the error::
*************************************************
OpenCV Error: Null pointer (NULL guiReceiver (please create a window)) in cvDestroyWindow, file /home/brian/opencv/modules/highgui/src/window_QT.cpp, line 497
terminate called after throwing an instance of 'cv::Exception'
what(): /home/brian/opencv/modules/highgui/src/window_QT.cpp:497: error: (-27) NULL guiReceiver (please create a window) in function cvDestroyWindow

The program has unexpectedly finished.
/home/brian/Scherady/build-htrack-Desktop-Default/htrack_atb crashed
***************************************************
Thank you

**Comment by ataiya** [comment]
2) that's *still* an OpenCV problem

We were *not* using the Qt version of highgui though. 
I think it was just the X11 (most basic) one.
 
It's possible there is an exception that happens only in the Qt version and not the other. Just from what I see it seems the function that closes a window behaves differently? I don't think we made sure the window existed before deleting it. That's just a guess... I'd have to run a debugger on your code to know...

**Comment by Scherady** [comment]
1) Just solved the problem and ran htrack OK :)
It looks like a bug in OpenCv/Qt. I modified windows_qt.cpp, in 
CV_IMPL void cvDestroyWindow(const char* name)
I replaced:
        CV_Error( CV_StsNullPtr, "NULL guiReceiver (please create a window)" );
by:
        return;
and rebuilt OpenCV.

2) First impression: yes hatrack performs much better under Ubuntu.

3) The real work starts now for me :)
